### ISSUE TITLE
Request user and password SEI_120G firmware update

### ISSUE THREAD

**Issue by Rodgelito** [binarykore/binarykore#1]
Hello sir good morning what is my username and password for my SEI_120g

**Comment by Rodgelito** [comment]
![Uploading Screenshot_2022-09-27-06-17-58-54_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by binarykore** [comment]
It is already a paid credentials account, I changed the username and password on purpose.. 1 USD or 50 PHP.. Just send it to my GCash..
